name: build
on:
  push:
#    branches:
#      - master
    paths:
      - "**.c"
      - "**.h"
      - "**.s"
      - ".github/workflows/build.yaml"
      - "*.txt"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

#      - name: cmake probe
#        run: cmake -?
#        shell: bash {0}

 #     - uses: actions/upload-artifact@v3.1.0
 #       with:
 #         name: ${{ matrix.config }}_${{ matrix.board }}_build
 #         path: |
 #           build/zephyr/merged.hex
