name: build
on:
  push:
#    branches:
#      - master
    paths:
      - "**.c"
      - "**.h"
      - "**.s"
      - ".github/workflows/build.yaml"
      - "*.txt"

jobs:
  build:
    name: stabilcd_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epsgamus/stm32cubeclt:0.1
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

      - name: st pkg list 
#        run: find / -type f -iname "stm32cubeclt*"
        run: ls /opt/st/stm32cubeclt_1.16.0 -a

      - name: st pkg dirs
#        run: find / -type f -iname "stm32cubeclt*"
        run: /opt/st/stm32cubeclt_1.16.0/STM32CubeCLT_metadata.sh

      - name: cmake 
        run: |
          PATH=$PATH:/opt/st/stm32cubeclt_1.16.0/Ninja/bin:/opt/st/stm32cubeclt_1.16.0/GNU-tools-for-STM32/bin
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_TOOLCHAIN_FILE=/__w/stabilcd/stabilcd/VSCode/stabilcd/cmake/gcc-arm-none-eabi.cmake -S/__w/stabilcd/stabilcd/VSCode/stabilcd -B/__w/stabilcd/stabilcd/VSCode/stabilcd/build -G Ninja
          cmake --build /__w/stabilcd/stabilcd/VSCode/stabilcd/build

      - name: elf list
        run: ls /__w/stabilcd/stabilcd/VSCode/stabilcd/build -a

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: stabilcd_build
          path: /__w/stabilcd/stabilcd/VSCode/stabilcd/build/debug/stabilcd.hex
