name: build
on:
  push:
#    branches:
#      - master
    paths:
      - "**.c"
      - "**.h"
      - "**.s"
      - ".github/workflows/build.yaml"
      - "*.txt"

jobs:
  build:
    name: stabilcd_build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

      - name: ls 
        run: ls ./VSCode/stabilcd/cmake -a
        shell: bash {0}


      - name: cmake probe
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/VSCode/stabilcd/cmake/gcc-arm-none-eabi.cmake -S./VSCode/stabilcd -B./VSCode/stabilcd/build/debug -G Ninja

 #     - name: Upload     
 #     - uses: actions/upload-artifact@v3.1.0
 #       with:
 #         name: ${{ matrix.config }}_${{ matrix.board }}_build
 #         path: |
 #           build/zephyr/merged.hex
