name: build
on:
  push:
#    branches:
#      - master
    paths:
      - "**.c"
      - "**.h"
      - "**.s"
      - ".github/workflows/build.yaml"
      - "*.txt"

jobs:
  build:
    name: stabilcd_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epsgamus/stm32cubeclt:0.1
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

#      - name: pull docker
#        run: docker pull ghcr.io/epsgamus/stm32cubeclt:0.1
#        shell: bash {0}

#      - name: run docker
#        run: docker run -it ghcr.io/epsgamus/stm32cubeclt:0.1 bash
#        shell: bash {0}

      - name: ls 
        run: find / -type f -iname "gcc-arm-none-eabi*"

      - name: cmake probe
        run: cmake -DPRESET_NAME=debug -DCMAKE_INSTALL_PREFIX=/__w/stabilcd/stabilcd/VSCode/stabilcd/build/debug/install -DCMAKE_TOOLCHAIN_FILE=/__w/stabilcd/stabilcd/VSCode/stabilcd/cmake/gcc-arm-none-eabi.cmake -S/__w/stabilcd/stabilcd/VSCode/stabilcd -B/__w/stabilcd/stabilcd/VSCode/stabilcd/build/debug
#cmake -DCMAKE_BUILD_TYPE=Debug -DPRESET_NAME=SKSB -DSK_SBMS=ON -DCMAKE_INSTALL_PREFIX=/opt/project/build/SKSB/install -DCMAKE_TOOLCHAIN_FILE:FILEPATH=/opt/project/cmake/gcc-arm-none-eabi.cmake -S/opt/project -B/opt/project/build/SKSB/build -G Ninja
#cmake --build /opt/project/build/SKSB/build


 #       run: cmake -S /home/runner/work/stabilcd/stabilcd/VSCode/stabilcd -B /home/runner/work/stabilcd/stabilcd/VSCode/stabilcd/build/debug --toolchain /home/runner/work/stabilcd/stabilcd/VSCode/stabilcd/cmake/gcc-arm-none-eabi.cmake

 #     - name: Upload     
 #     - uses: actions/upload-artifact@v3.1.0
 #       with:
 #         name: ${{ matrix.config }}_${{ matrix.board }}_build
 #         path: |
 #           build/zephyr/merged.hex
