name: build
on:
  push:
#    branches:
#      - master
    paths:
      - "**.c"
      - "**.h"
      - "**.s"
      - ".github/workflows/build.yaml"
      - "*.txt"

jobs:
  build:
    name: stabilcd_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epsgamus/stm32cubeclt:0.1
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0

#      - name: pull docker
#        run: docker pull ghcr.io/epsgamus/stm32cubeclt:0.1
#        shell: bash {0}

#      - name: run docker
#        run: docker run -it ghcr.io/epsgamus/stm32cubeclt:0.1 bash
#        shell: bash {0}

      - name: ls 
        run: ls -a
        shell: bash {0}

 #     - name: cmake probe
 #       run: cmake -D CMAKE_BUILD_TYPE=Debug --toolchain ./VSCode/stabilcd/cmake/gcc-arm-none-eabi.cmake -S ./VSCode/stabilcd -B ./VSCode/stabilcd/build/debug -- target stabilcd
 #       run: cmake -S /home/runner/work/stabilcd/stabilcd/VSCode/stabilcd -B /home/runner/work/stabilcd/stabilcd/VSCode/stabilcd/build/debug --toolchain /home/runner/work/stabilcd/stabilcd/VSCode/stabilcd/cmake/gcc-arm-none-eabi.cmake

 #     - name: Upload     
 #     - uses: actions/upload-artifact@v3.1.0
 #       with:
 #         name: ${{ matrix.config }}_${{ matrix.board }}_build
 #         path: |
 #           build/zephyr/merged.hex
